ruby 1.8.6 (2009-3-4 mbari 8B/0x8770 on patchlevel 287) [i686-linux]
#0:crash.rb:1::-: def go2(a, b)
 |#0:crash.rb:1:Module:>: def go2(a, b)
args were []
#0:crash.rb:1:Module:<: def go2(a, b)
#0:crash.rb:5::-: def go(a); 
 |#0:crash.rb:5:Module:>: def go(a); 
args were []
#0:crash.rb:5:Module:<: def go(a); 
#0:crash.rb:9::-: go '3'
 |#0:crash.rb:5:Object:>: def go(a); 
args were [["a", "3"]]
 |#0:crash.rb:6:Object:-:  go2(a, 55); 
 | |#0:crash.rb:1:Object:>: def go2(a, b)
args were [["a", "3"], ["b", 55]]
 | |#0:crash.rb:2:Object:-:  raise
 | | |#0:crash.rb:2:Kernel:>:  raise
args were []
 | | | |#0:crash.rb:2:Class:>:  raise
args were []
 | | | | |#0:crash.rb:2:Exception:>:  raise
args were []
 | | | |#0:crash.rb:2:Exception:<:  raise
 | | |#0:crash.rb:2:Class:<:  raise
 | | | |#0:crash.rb:2:Exception:>:  raise
args were []
 | | |#0:crash.rb:2:Exception:<:  raise
 | | | |#0:crash.rb:2:Exception:>:  raise
args were []
 | | |#0:crash.rb:2:Exception:<:  raise
 | | |#0:crash.rb:2:Object:R:  raise
 | |#0:crash.rb:2:Kernel:<:  raise
 |#0:crash.rb:3:Object:<: end
#0:crash.rb:7:Object:<: end

unhandled exception: crash.rb:2:   raise
	locals: {"a"=>"3", "b"=>55}
	  from:
	crash.rb:1 go2(a=>3, b=>55)
		locals: {"a"=>"3", "b"=>55}
	crash.rb:5 go(a=>3)
		locals: {"a"=>"3"}
